### PR TITLE
Partial dockerize development environment

### PR DESCRIPTION
**Pull request by luislavena**
Aim to simplify local development:

* Dockerize PHP 5.6 using Apache in order to reduce the number of local dependencies.
* Lock Node packages (using Yarn) to ensure consistent versioning across environments
* Updated the generated CSS

Requirements:

* Docker & docker-compose

Usage:

* Build image using `docker-compose build web`
* Boot PHP application using `docker-compose up web`
* Use Ctrl+C or `docker-compose down` from another terminal window
* Install assets within the default theme using `yarn install`
* Replace `grunt init` and `grunt build` with `yarn run grunt:init` and `yarn run grunt:build` respectively.

/cc @mubashariqbal @mrdoinel

### CODE REVIEW

**Comment by luislavena** [comment]
Hello @mrdoinel @ifox, the only biggest change in this PR is the usage of `yarn` instead of plain `npm` for theme installation.

Still far from ideal scenario (mix of docker container for PHP and native Node for building the theme), but seems to be working properly.

Looking forward your comments.
❤️ ❤️ ❤️

**Comment by ifox** [comment]
This is great thanks @luislavena!

The only thing I noticed is that the generated css is missing some browser prefixes but most are most likely not needed anymore and it is probably because the updated autoprefixer dependency has updated rules, right?

**Comment by luislavena** [comment]
Yeah @ifox, noticed the same thing, so asked @mrdoinel to review a previous patch of this before submitting the PR.

🏓 @mrdoinel ?

**Comment by mrdoinel** [comment]
Yeah this is fine : we dont need webkit prefix anymore for the CSS animations (since at least version 9).

**Comment by luislavena** [comment]
Great, thank you @mrdoinel! 🎉 

If you have no further objections @ifox, I would like to get this merged.

Thank you!
❤️ ❤️ ❤️

**Pull request merged**
